# Generated by Django 2.2.5 on 2020-07-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('created_dt', models.DateField()),
            ],
        ),
    ]
