# Generated by Django 2.2.5 on 2020-07-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200704_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
